### ISSUE TITLE
Support Ansible

### ISSUE THREAD

**Issue by robinro** [yast/yast-configuration-management#9]
Ansible is quite commonly used for configuration management. It also supports "pull" and can thus be used for initial deployments and we use it together with autoyast.
Therefore there should be support to use ansible with the new configuration_management setup.

Potential arguments:
```
<configuration_management>
  <type>ansible</type>
  <pull_url>https://my.server.example.com/repo</pull_url>
  <pull_key></pull_key> <!-- ssh key if connection is via ssh -->
  <playbook>autoyast.yml</playbook>
</configuration_management>
```

It's probably a good idea to also have a field `extra_args` to pass more command line options to ansible.

**Comment by imobachgs** [comment]
Hi @robinro,

Yes, it sounds good. Could you, please, open a FATE at https://features.opensuse.org/ ?

On the other hand, I really like the idea of having an `extra_args`. It could be also used by all the providers (like Salt and Puppet).

Thanks!

**Comment by robinro** [comment]
Moved this to https://features.opensuse.org/323929

**Comment by imobachgs** [comment]
Thanks a lot!
